Repository timber/timber, pull requests merged in 2018-11, with the labels that each got.

#1856 Update contributors list
  README.md
Labels: docs

#1854 ref #1849 -- add docs to clarify WEBP behaviors
  lib/Image/Operation/ToWebp.php
  lib/ImageHelper.php
Labels: docs

#1846 Implementing maybe_convert_array to all class functions in Timber/Twig
  lib/Twig.php
Labels: 2.0

#1829 2.x Documentation updates
  docs/_index.md
  docs/guides/cheatsheet.md
  docs/guides/context.md
  docs/guides/cookbook-images.md
  docs/guides/cookbook-text.md
  docs/guides/cookbook-twig.md
  docs/guides/custom-fields.md
  docs/guides/custom-page-templates.md
  docs/guides/debugging.md
  docs/guides/escaping.md
  docs/guides/extending-timber.md
  docs/guides/filters.md
  docs/guides/functions.md
  docs/guides/internationalization.md
  docs/guides/menus.md
  docs/guides/pagination.md
  docs/guides/performance.md
  docs/guides/routing.md
  docs/guides/sidebars.md
  docs/guides/template-locations.md
  docs/guides/unit-testing.md
  docs/guides/woocommerce.md
  docs/guides/wp-integration.md
  docs/integrations/advanced-custom-fields.md
  docs/upgrade-guides/2.0.md
  lib/PostQuery.php
Labels: 2.0, docs

#1859 2.x Remove deprecated functionality in $post->terms()
  lib/Post.php
  tests/test-timber-post-terms.php
  tests/test-timber-post.php
Labels: 2.0
