Repository timber/timber, pull requests merged in 2019-07, with the labels that each got.

#2042 Deprecated some internal image functions
  lib/Image.php
Labels: 2.0, Ready for Review

#1943 Deprecate fetch
  lib/Timber.php
Labels: 2.0

#2046 Add details regarding Timber::cache to docs
  docs/guides/performance.md
  docs/guides/routing.md
Labels: docs
