Repository timber/timber, pull requests merged in 2019-06, with the labels that each got.

#2021 ref #2020 -- revert Twig version
  composer.json
Labels: 1.x

#2018 Menu optimizations
  lib/Menu.php
  lib/MenuItem.php
  readme.txt
  tests/test-timber-menu.php
Labels: 1.x, Ready for Review

#1969 feat: Term::from handling multiple terms
  lib/Term.php
  tests/test-timber-term.php
Labels: 1.x

#2022 Release of 1.10.0 and resolution of WPML errors
  composer.json
  lib/Timber.php
  readme.txt
Labels: Ready for Review

#2019 Streamline get_meta_values functions across objects
  lib/Comment.php
  lib/Post.php
  lib/Term.php
  lib/User.php
  tests/test-timber-comment.php
  tests/test-timber-post.php
  tests/test-timber-term.php
  tests/test-timber-user.php
Labels: 2.0, Ready for Review

#1996 2.x Remove unneeded use statements
  lib/Archives.php
  lib/Comment.php
  lib/CommentThread.php
  lib/FunctionWrapper.php
  lib/Helper.php
  lib/Image/Operation/ToJpg.php
  lib/Image/Operation/ToWebp.php
  lib/ImageHelper.php
  lib/Loader.php
  lib/Menu.php
  lib/MenuItem.php
  lib/Post.php
  lib/PostCollection.php
  lib/PostGetter.php
  lib/PostQuery.php
  lib/QueryIterator.php
  lib/Request.php
  lib/Site.php
  lib/Term.php
  lib/TermGetter.php
  lib/Theme.php
  lib/Timber.php
  lib/Twig.php
  lib/User.php
Labels: 2.0

#1965 2.x Update Twig to namespaced classes, drop backwards compatibility
  composer.json
  docs/guides/extending-timber.md
  docs/guides/functions.md
  docs/guides/performance.md
  docs/upgrade-guides/2.0.md
  lib/Cache/KeyGenerator.php
  lib/Cache/WPObjectCacheAdapter.php
  lib/Loader.php
  lib/Timber.php
  lib/Twig.php
  lib/Twig_Filter.php
  lib/Twig_Function.php
  tests/test-timber-function-wrapper.php
  tests/test-timber-twig.php
Labels: 2.0, Ready for Review

#2031 2.x Update .travis.yml
  .travis.yml
Labels: 2.0

#1997 2.x Deprecate Twig environment option variables
  .travis.yml
  docs/guides/escaping.md
  docs/guides/performance.md
  docs/upgrade-guides/2.0.md
  lib/Loader.php
  lib/Timber.php
  tests/test-timber-cache.php
  tests/test-timber-integrations.php
  tests/test-timber-twig.php
Labels: 2.0

#2032 Ref #2027 – Improve documentation for magic core methods, fix tests
  docs/guides/custom-fields.md
  lib/Core.php
  tests/test-timber-post-getter.php
  tests/test-timber-term.php
Labels: 2.0, Ready for Review

#2027 [WIP] 2.x Improve magic methods in Core
  lib/Core.php
Labels: 2.0, wip

#2015 ref #1731 -- apply suggested fix for comment order override
  lib/CommentThread.php
  readme.txt
Labels: 1.x, Ready for Review

#2013 1974 wpml menu fix
  lib/Menu.php
  readme.txt
Labels: 1.x, Ready for Review
