Repository timber/timber, pull requests merged in 2020-01, with the labels that each got.

#2124 Twig filter
  composer.json
  lib/Helper.php
  lib/Twig.php
  tests/test-timber-helper.php
Labels: wip

#2138 Improve inline documentation for Timber\PathHelper
  lib/PathHelper.php
Labels: docs

#2017 Static analysis fixes
  lib/Helper.php
  lib/Integrations.php
  lib/Post.php
  lib/PostType.php
  lib/Timber.php
Labels: 2.0

#2146 2.x Improve Helper::deprecated()
  lib/Helper.php
Labels: 2.0

#2148 2.x factories test fixes
  tests/test-timber-meta.php
Labels: 2.0

#2136 2.x Add a Date/Time guide
  docs/guides/date-time.md
  docs/upgrade-guides/2.0.md
Labels: 2.0

#2159 2.x Fix deprecated() function
  lib/Helper.php
Labels: 2.0

#2135 2.x Add compatibility for Twig date functionality
  docs/guides/date-time.md
  docs/upgrade-guides/2.0.md
  lib/DateTimeHelper.php
  lib/Timber.php
  lib/Twig.php
  tests/test-timber-dates.php
  tests/test-timber-twig-date-filter-default.php
  tests/test-timber-twig-date-filter-immutable.php
  tests/test-timber-twig-date-filter-interval.php
  tests/test-timber-twig-date-filter-timber.php
  tests/test-timber-twig-date-filter.php
  tests/test-timber-twig-date-function.php
  tests/test-timber-twig-filters.php
Labels: 2.0

#2158 #2153 add a test helper for auto-removing filters
  tests/Timber_UnitTestCase.php
  tests/test-timber-meta.php
Labels: 2.0, testing

#2156 Provide notice for min. WordPress version
  composer.json
  docs/upgrade-guides/2.0.md
  lib/Admin.php
  tests/test-timber-admin.php
Labels: 2.0

#2137 2.x Update post.date
  lib/DateTimeHelper.php
  lib/DatedInterface.php
  lib/Post.php
  lib/Twig.php
  tests/test-timber-dates.php
Labels: 2.0

#2161 A little more 2.x test coverage
  lib/Timber.php
  tests/test-timber-filters.php
Labels: 2.0

#2149 Introduce PHPStan
  .travis.yml
  composer.json
  docs/guides/testing.md
  phpstan.neon
  tests/phpstan/bootstrap.php
  tests/phpstan/wp-cli-stubs-2.2.0.php
Labels: 2.x Future, testing

#2165 Szepeviktor phpstan level 1
  .travis.yml
  lib/ImageHelper.php
  phpstan.neon
  tests/phpstan/bootstrap.php
Labels: 2.0, testing

#2150 2.x Optimize post date filters
  lib/Post.php
Labels: 2.0

#2168 2.x User factories DocBlocks
  lib/Factory/UserFactory.php
  lib/Timber.php
Labels: 2.0

#2167 2.x Add a Users Guide
  docs/guides/class-maps.md
  docs/guides/users.md
Labels: 2.0

#2160 2.x user factories
  lib/Comment.php
  lib/Factory/CommentFactory.php
  lib/Factory/UserFactory.php
  lib/Helper.php
  lib/Integrations.php
  lib/Integrations/CoAuthorsPlus.php
  lib/Post.php
  lib/Timber.php
  lib/Twig.php
  lib/User.php
  tests/Timber_UnitTestCase.php
  tests/test-comment-factory.php
  tests/test-post-factory.php
  tests/test-term-factory.php
  tests/test-timber-helper.php
  tests/test-timber-integration-acf.php
  tests/test-timber-integrations-coauthors.php
  tests/test-timber-integrations.php
  tests/test-timber-meta-deprecated.php
  tests/test-timber-meta.php
  tests/test-timber-post.php
  tests/test-timber-properties.php
  tests/test-timber-twig-objects.php
  tests/test-timber-user.php
  tests/test-timber.php
  tests/test-user-factory.php
Labels: 2.0
