Repository timber/timber, pull requests merged in 2020-12, with the labels that each got.

#2383 📝 Add to menus.md: Code samples using > 1 menu
  docs/guides/menus.md
Labels: docs

#2384 2.x Documentation Typos
  docs/v2/installation/manage-timber-with-composer.md
  docs/v2/upgrade-guides/2.0.md
Labels: 2.0, docs

#2375 2.x Add options to better control read_more and end behavior in post excerpts
  docs/v2/upgrade-guides/2.0.md
  lib/PostExcerpt.php
  tests/test-timber-post-excerpt-object.php
  tests/test-timber-post-excerpt.php
Labels: 2.0

#2389 2.x Documentation fixes
  docs/v1/guides/acf-cookbook.md
  docs/v2/upgrade-guides/2.0.md
Labels: 2.0

#2376 2.x Use a subdirectory for sideloaded images
  docs/v2/guides/cookbook-images.md
  docs/v2/upgrade-guides/2.0.md
  lib/ImageHelper.php
  tests/test-timber-image-helper.php
  tests/test-timber-image-letterbox.php
  tests/test-timber-image-resize.php
  tests/test-timber-image-tojpg.php
  tests/test-timber-image-towebp.php
  tests/test-timber-image.php
Labels: 2.0
