Repository timber/timber, pull requests merged in 2020-06, with the labels that each got.

#2254 2.x Add documentation for new Pages Menu API
  docs/guides/class-maps.md
  docs/guides/menus.md
  docs/upgrade-guides/2.0.md
Labels: 2.0

#2257 Use speedy pcov instead of xdebug
  .travis.yml
Labels: 2.x Future

#2270 2.x Fix some URLs in documentation
  docs/v2/getting-started/setup.md
  docs/v2/getting-started/video-tutorials.md
  docs/v2/guides/context.md
  docs/v2/guides/cookbook-images.md
  docs/v2/guides/cookbook-text.md
  docs/v2/guides/custom-fields.md
  docs/v2/guides/functions.md
  docs/v2/guides/internationalization.md
  docs/v2/guides/performance.md
  docs/v2/guides/wp-integration.md
  docs/v2/upgrade-guides/2.0.md
Labels: 2.0

#2265 codecov should make tests fail
  .travis.yml
  composer.json
  phpunit-nocover.xml
  phpunit.xml
Labels: 2.0

#2266 codecov should make tests fail v1
  .travis.yml
Labels: 1.x

#2260 2.x Update Extending Timber Guide
  docs/v2/guides/extending-timber.md
Labels: 2.0

#2169 2.x Add Timber::get_post_by()
  docs/v2/upgrade-guides/2.0.md
  lib/Timber.php
  tests/test-timber.php
Labels: 2.0

#2259 2.x Update documentation for Getting Started
  README.md
  docs/_index.md
  docs/v2/getting-started/a-post-archive.md
  docs/v2/getting-started/a-single-post.md
  docs/v2/getting-started/introduction.md
  docs/v2/getting-started/setup.md
  docs/v2/getting-started/template-inheritance-and-includes.md
  docs/v2/getting-started/theming.md
  docs/v2/getting-started/twig-tools.md
  docs/v2/getting-started/video-tutorials.md
  docs/v2/guides/cookbook-twig.md
  docs/v2/guides/date-time.md
  docs/v2/guides/template-locations.md
  docs/v2/guides/wp-integration.md
  docs/v2/index.md
  docs/v2/installation/installation.md
  docs/v2/upgrade-guides/2.0.md
Labels: 2.0

#2282 Provide a non-functional definition for Twig's `dump` function
  lib/Loader.php
  readme.txt
Labels: 1.x
