Repository timber/timber, pull requests merged in 2021-04, with the labels that each got.

#2391 Introduce Timber::get_term_by() method
  docs/v2/guides/terms.md
  docs/v2/upgrade-guides/2.0.md
  lib/Timber.php
  lib/Twig.php
  tests/test-term-factory.php
  tests/test-timber-term-factories.php
  tests/test-timber-theme.php
Labels: 2.0

#2406 Handle search, tax queries in ::context()
  docs/v2/guides/context.md
  docs/v2/upgrade-guides/2.0.md
  lib/Timber.php
  tests/test-timber-context.php
Labels: 2.0

#2398 Run CI on Graviton
  .travis.yml
Labels: 2.x Future, testing

#2437 Remove unused method Post::check_post_id()
  lib/Post.php
Labels: 2.0

#2393 #2368 – Update context format in documentation
  docs/v2/guides/context.md
  docs/v2/guides/cookbook-images.md
  docs/v2/guides/gutenberg.md
  docs/v2/guides/pagination.md
  docs/v2/guides/performance.md
  docs/v2/guides/sidebars.md
  docs/v2/guides/wp-integration.md
  docs/v2/integrations/advanced-custom-fields.md
  docs/v2/upgrade-guides/2.0.md
  lib/Helper.php
  lib/Image.php
  lib/Site.php
  lib/Theme.php
  lib/Timber.php
Labels: 2.0

#2431 Lando environment
  .lando.yml
  lando-config/scripts/install-wp-tests.sh
  lando-config/scripts/setup-wordpress.sh
Labels: 2.x Future, needs-unit-test

#2438 Fix MenuItem creation
  lib/Factory/MenuItemFactory.php
  lib/MenuItem.php
  tests/test-timber-menu.php
Labels: 2.0

#2440 Add patch for SVG dimensions
  lib/Factory/PostFactory.php
  lib/Image.php
  tests/test-timber-image.php
Labels: 2.0, Ready for Review

#2439 URLHelper::get_params() return value
  docs/v2/upgrade-guides/2.0.md
  lib/URLHelper.php
  tests/test-timber-url-helper.php
Labels: 2.0
