Repository timber/timber, pull requests merged in 2021-09, with the labels that each got.

#2480 #2417 Add GitHub Actions for 2.x and update version requirements
  .editorconfig
  .github/workflows/test.yml
  .travis.yml
  CONTRIBUTING.md
  README.md
  bin/install-wp-tests.sh
  composer.json
  lib/Twig.php
  tests/assets/test-shortcodes.twig
  tests/bootstrap.php
  tests/test-timber-helper.php
  tests/test-timber-image-resize.php
  tests/test-timber-image.php
  tests/test-timber-loader.php
  tests/test-timber-twig.php
Labels: 2.0

#2478 Fix bug when using switch_to_blog() in combination with Timber images
  lib/Image.php
  readme.txt
  tests/test-timber-multisite.php
Labels: 1.x

#2463 Fix the `thumbnail()` method return type
  lib/Post.php
  readme.txt
Labels: 1.x

#2469 2.x Improve routing docs
  docs/v2/guides/routing.md
  docs/v2/upgrade-guides/2.0.md
Labels: docs, 2.0

#2479 2.x Add hint about checking for Timber’s version
  docs/v2/upgrade-guides/2.0.md
Labels: docs, 2.0

#2408 #2192 - Allow users to filter Timber default Twig functions
  lib/Twig.php
  tests/test-timber-twig.php
Labels: 2.0, Ready for Review

#2379 2.x Improve documentation for terms
  docs/v2/guides/terms.md
  docs/v2/upgrade-guides/2.0.md
  lib/Timber.php
Labels: docs, 2.0

#2485 Fix a test failing with 2.x + Multisite
  tests/test-timber-multisite.php
Labels: 2.0

#2484 Merge in 2.x GH Actions changes
  .github/workflows/test.yml
  .travis.yml
  bin/install-wp-tests.sh
  composer.json
  tests/bootstrap.php
Labels: 1.x

#2471 2.x Update Twig documentation
  docs/redirects.njk
  docs/v1/getting-started/theming.md
  docs/v1/guides/cookbook-images.md
  docs/v1/guides/escapers.md
  docs/v1/guides/filters.md
  docs/v2/getting-started/a-single-post.md
  docs/v2/getting-started/template-inheritance-and-includes.md
  docs/v2/guides/cookbook-images.md
  docs/v2/guides/cookbook-twig.md
  docs/v2/guides/escaping.md
  docs/v2/guides/filters.md
  docs/v2/guides/posts.md
  docs/v2/guides/shortcodes.md
  docs/v2/guides/template-locations.md
  docs/v2/guides/twig-filters.md
  docs/v2/guides/twig.md
  docs/v2/guides/widgets.md
  docs/v2/guides/wp-integration.md
Labels: docs, 2.0

#2293 2.x Deprecate Timber\PostClassMap filter and rename it to timber/post/classmap
  docs/v2/upgrade-guides/2.0.md
  lib/Factory/PostFactory.php
  tests/test-post-factory.php
Labels: 2.0

#2419 2.x Update timber/twig/… filters
  docs/v2/guides/extending-timber.md
  docs/v2/guides/extending-twig.md
  docs/v2/guides/functions.md
  docs/v2/upgrade-guides/2.0.md
  lib/Loader.php
  lib/Twig.php
  tests/test-timber-function-wrapper.php
  tests/test-timber-twig.php
Labels: 2.0

#2488 Adds @nlemoine to the contribs list!
  README.md
Labels: 1.x

#2397 2.x improve meta field handling
  lib/Attachment.php
  lib/Comment.php
  lib/CoreEntity.php
  lib/Image.php
  lib/Integrations/ACF.php
  lib/Post.php
  lib/Term.php
  lib/User.php
  tests/test-timber-integration-acf.php
Labels: 2.0

#2490 2.x Fix bug when page_on_front is not set in some cases
  lib/Timber.php
  tests/test-timber-context.php
Labels: 2.0

#2405 Integrations API
  docs/v2/guides/custom-integrations.md
  docs/v2/upgrade-guides/2.0.md
  lib/Integration/AcfIntegration.php
  lib/Integration/CoAuthorsPlus/CoAuthorsPlusUser.php
  lib/Integration/CoAuthorsPlusIntegration.php
  lib/Integration/IntegrationInterface.php
  lib/Integration/WpmlIntegration.php
  lib/Integrations.php
  lib/Timber.php
  tests/bootstrap.php
  tests/test-timber-image-resize.php
  tests/test-timber-integration-acf.php
  tests/test-timber-integration-wpml.php
  tests/test-timber-integrations-coauthors.php
  tests/test-timber-integrations.php
  tests/test-timber-menu.php
  tests/test-timber-meta-deprecated.php
  tests/test-timber-meta.php
  tests/test-timber-url-helper.php
  tests/test-timber-user.php
  tests/test-timber-wpml.php
Labels: 2.0

#2498 Fix transforms on file and image
  lib/Integration/AcfIntegration.php
  tests/test-timber-integration-acf.php
Labels: 2.0
