Repository timber/timber, pull requests merged in 2022-06, with the labels that each got.

#2545 2.x Don’t overwrite post global
  lib/Post.php
Labels: 2.0, testing

#2591 2.x Use assertTrue() and get_class() instead of assertInstanceOf() in certain tests
  tests/test-comment-factory.php
  tests/test-post-factory.php
  tests/test-term-factory.php
  tests/test-user-factory.php
Labels: 2.0

#2562 2.x Implement new PagesMenu API
  docs/v2/guides/class-maps.md
  docs/v2/upgrade-guides/2.0.md
  lib/Factory/MenuFactory.php
  lib/Factory/PagesMenuFactory.php
  lib/Menu.php
  lib/PagesMenu.php
  lib/Timber.php
  tests/test-pages-menu-factory.php
  tests/test-timber-pages-menu.php
Labels: 2.0

#2565 2.x Update Upgrade Guide with Twig deprecations
  docs/v2/guides/twig.md
  docs/v2/upgrade-guides/2.0.md
Labels: 2.0

#2595 Use newest version of Upstatement/routes
  composer.json
Labels: 1.x
