Repository timber/timber, pull requests merged in 2022-04, with the labels that each got.

#2563 Test against Latest WP Version instead of Trunk
  .github/workflows/test.yml
Labels: 2.0, testing

#2550 Improve composer version ranges
  composer.json
Labels: 1.x

#2546 2.x Remove twig/cache-extension, add support for twig/cache-extra
  composer.json
  docs/v2/guides/performance.md
  docs/v2/upgrade-guides/2.0.md
  lib/Cache/KeyGenerator.php
  lib/Cache/WPObjectCacheAdapter.php
  lib/Loader.php
  tests/test-timber-cache-extra.php
  tests/test-timber-cache.php
Labels: 2.0
