Repository timber/timber, pull requests merged in 2023-05, with the labels that each got.

#2732 Update 2.0.md - fix 404 link to setup guide
  docs/v2/upgrade-guides/2.0.md
Labels: 2.0

#2736 Add workflow to check docs links
  .github/workflows/links.yml
Labels: 2.0

#2667 2.x Fix PHPStan issues on level 1
  phpstan.neon
  src/Menu.php
  src/MenuItem.php
  src/User.php
Labels: 2.0, Ready for Review

#2743 Update broken links in documentation
  docs/v1/getting-started/theming.md
  docs/v1/guides/cookbook-images.md
  docs/v1/guides/custom-page-templates.md
  docs/v1/guides/internationalization.md
  docs/v2/getting-started/a-post-archive.md
  docs/v2/getting-started/a-single-post.md
  docs/v2/guides/cookbook-images.md
  docs/v2/guides/custom-fields.md
  docs/v2/guides/custom-page-templates.md
  docs/v2/guides/internationalization.md
  docs/v2/guides/menus.md
  docs/v2/guides/performance.md
  docs/v2/guides/posts.md
  docs/v2/upgrade-guides/2.0.md
Labels: 2.0

#2669 2.x Remove unneeded Timber\Image::is_image() method
  docs/v2/upgrade-guides/2.0.md
  src/Image.php
Labels: 2.0, Ready for Review

#2730 Fix `PostFactory::is_image` incorrectly using `wp_check_filetype`
  src/Factory/PostFactory.php
Labels: help wanted, needs-unit-test, 2.0, Ready for Review

#2746 Add @api tag to Helper
  src/Helper.php
Labels: 2.0

#2660 2.x Make object constructors final
  docs/v2/upgrade-guides/2.0.md
  src/Comment.php
  src/Menu.php
  src/MenuItem.php
  src/PagesMenu.php
  src/Post.php
  src/Term.php
  src/User.php
Labels: 2.0, Ready for Review

#2744 Update property and method docblocks in Theme.php.
  src/Theme.php
Labels: 2.0

#2752 2.x Merge in latest changes from master branch
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: 2.0

#2754 2.x Remove unused param from `Timber\Term::build()`
  src/Term.php
Labels: 2.0

#2749 Fix custom field test
  tests/test-timber-meta.php
  tests/test-timber-post.php
Labels: 2.0

#2750 Remove audio & video methods from `Post`
  src/Post.php
  tests/test-timber-post.php
Labels: 2.0

#2668 2.x Fix PHPStan issues on level 2
  composer.json
  phpstan.neon
  src/AccessesPostsLazily.php
  src/Core.php
  src/Factory/PagesMenuFactory.php
  src/Helper.php
  src/Image/Operation/Resize.php
  src/ImageHelper.php
  src/Integration/CoAuthorsPlus/CoAuthorsPlusUser.php
  src/Menu.php
  src/MenuItem.php
  src/PagesMenu.php
  src/Pagination.php
  src/Post.php
  src/PostArrayObject.php
  src/Site.php
  src/Term.php
  src/Timber.php
  tests/phpstan/WPNavMenuItemPost.php
  tests/phpstan/WPPostPropertyReflection.php
Labels: 2.0, Ready for Review

#2755 2.x Update Upgrade Guide for #2750
  docs/v2/upgrade-guides/2.0.md
Labels: 2.0

#2761 2.x Fix some small issues in Getting Started docs
  docs/v2/getting-started/a-post-archive.md
  docs/v2/getting-started/introduction.md
  docs/v2/getting-started/template-inheritance-and-includes.md
Labels: docs, 2.0
