Repository timber/timber, pull requests merged in 2023-10, with the labels that each got.

#2787 docs(cheatcheat): Explained theme path, link and uri helpers.
  docs/v2/guides/cheatsheet.md
Labels: docs, 2.0

#2821 2.x Merge master branch
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  composer.json
  docs/v1/getting-started/setup.md
  docs/v1/getting-started/switch-to-composer.md
Labels: 2.0

#2818 fix: initialize typed properties correctly in ExternalImage::build()
  src/ExternalImage.php
  tests/test-external-image.php
Labels: has-patch, 2.0

#2806 fix: consider 'fields' value when returning terms from query
  src/Factory/TermFactory.php
  tests/test-term-factory.php
Labels: 2.0

#2798 V2 site overwrite magic __call method
  src/Core.php
  src/Site.php
  tests/test-timber-site.php
Labels: bug, 2.0

#2827 2.x Revert final constructors
  docs/v2/upgrade-guides/2.0.md
  src/Comment.php
  src/ExternalImage.php
  src/Menu.php
  src/MenuItem.php
  src/Post.php
  src/Term.php
  src/User.php
Labels: 2.0

#2828 fix: exclude tests from PHPStan
  phpstan.neon
Labels: 2.0

#2797 docs: Update v2 caching docs
  docs/v2/guides/performance.md
  src/Timber.php
Labels: docs, 2.0
