Repository timber/timber, pull requests merged in 2023-03, with the labels that each got.

#2664 2.x Remove unused Term::get_term_from_query() function
  docs/v2/upgrade-guides/2.0.md
  src/Term.php
Labels: 2.0, Ready for Review

#2641 Improve GitHub pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Ready for Review

#2712 Fix post preview
  src/Factory/PostFactory.php
  src/Timber.php
Labels: 2.0

#2705 2.x Fix menu item compatibility with WPML
  src/Integration/WpmlIntegration.php
  src/Menu.php
  tests/test-timber-menu.php
Labels: 2.0

#2717 2.x Add doing_it_wrong not for `numberposts` in Timber::get_posts()
  docs/v2/guides/custom-fields.md
  src/Post.php
  src/Timber.php
  tests/test-timber.php
Labels: 2.0

#2684 2.x Fix hint about Co-Authors Plus in Upgrade Guide
  docs/v2/upgrade-guides/2.0.md
Labels: docs, 2.0, Ready for Review

#2720 Improve scheme detection and take advantage of WP native functions
  src/URLHelper.php
Labels: 2.0

#2719 Remove string helpers
  composer.json
  docs/v2/upgrade-guides/2.0.md
  src/ImageHelper.php
  src/Post.php
  src/TextHelper.php
  tests/test-timber-text-helper.php
Labels: 2.0
