Repository timber/timber, pull requests merged in 2024-01, with the labels that each got.

#2886 Fix phpstan tests
  phpstan.neon
Labels: 2.0, testing

#2894 feat: bump php-stubs/acf-pro-stubs to ^6.0
  composer.json
Labels: 2.0

#2860 Fix dynamic properties warnings
  lib/Core.php
  lib/Integrations.php
  lib/PostType.php
Labels: 1.x

#2856 2x. Update composer.json
  composer.json
Labels: 2.0

#2725 2.x Add ImageHelper filters to customize paths
  bin/install-wp-tests.sh
  src/ImageHelper.php
  tests/test-timber-image-helper-internals.php
  tests/test-timber-image-helper.php
Labels: 2.0, Ready for Review

#2865 Update ToWebp.php
  lib/Image/Operation/ToWebp.php
Labels: 1.x

#2893 feat: update ECS config and apply standards
  ecs.php
  src/AccessesPostsLazily.php
  src/Cache/WPObjectCacheAdapter.php
  src/Comment.php
  src/CoreEntity.php
  src/Factory/CommentFactory.php
  src/Factory/MenuItemFactory.php
  src/Factory/PagesMenuFactory.php
  src/Factory/PostFactory.php
  src/Factory/TermFactory.php
  src/Factory/UserFactory.php
  src/ImageHelper.php
  src/Integration/AcfIntegration.php
  src/Integration/CoAuthorsPlus/CoAuthorsPlusUser.php
  src/Integration/CoAuthorsPlusIntegration.php
  src/Loader.php
  src/Menu.php
  src/MenuItem.php
  src/PagesMenu.php
  src/Post.php
  src/PostExcerpt.php
  src/PostQuery.php
  src/PostsIterator.php
  src/Setupable.php
  src/Site.php
  src/Term.php
  src/Theme.php
  src/Timber.php
  src/Twig.php
  src/User.php
  tests/Timber_UnitTestCase.php
  tests/assets/Sport.php
  tests/bootstrap.php
  tests/php/SerializablePost.php
  tests/php/timber-custom-comment.php
  tests/test-comment-factory.php
  tests/test-image-dimensions.php
  tests/test-pages-menu-factory.php
  tests/test-timber-cache.php
  tests/test-timber-dates.php
  tests/test-timber-function-wrapper.php
  tests/test-timber-helper.php
  tests/test-timber-image-helper.php
  tests/test-timber-image.php
  tests/test-timber-loader.php
  tests/test-timber-menu.php
  tests/test-timber-meta.php
  tests/test-timber-post-iterator.php
  tests/test-timber-site.php
  tests/test-timber-term.php
  tests/test-timber-theme.php
  tests/test-timber-twig-date-filter-immutable.php
  tests/test-timber-twig-date-filter-interval.php
  tests/test-timber-twig-date-filter.php
  tests/test-timber-twig-date-function.php
  tests/test-timber-twig.php
  tests/test-user-factory.php
  tests/timber-mock-classes.php
Labels: 2.0

#2898 docs: Document filters and some methods
  src/Factory/CommentFactory.php
  src/Factory/PostFactory.php
  src/Factory/TermFactory.php
  src/Helper.php
  src/LocationManager.php
  src/Post.php
  src/Term.php
  src/Timber.php
  src/URLHelper.php
Labels: docs, 2.0
