Repository timber/timber, pull requests merged in 2024-02, with the labels that each got.

#2840 [Docs] Use recommended method to get meta in ACF Integration sample code
  docs/v2/integrations/advanced-custom-fields.md
Labels: docs

#2786 fix: Allow overwrite of default avatar in comments.
  src/Comment.php
Labels: 2.0

#2578 Allow the Timber\PostPreview::read_more to accept a boolean value
  lib/PostPreview.php
Labels: 2.0

#2930 docs: Fixes example query in upgrade guide
  docs/v2/upgrade-guides/2.0.md
Labels: 2.0

#2781 Prevent unneeded blog switching in multisite env.
  src/Site.php
  tests/test-timber-multisite.php
Labels: 2.0

#2863 feat: allow pagination object to be generated using $prefs only
  src/Pagination.php
Labels: 2.0

#2934 2.x Fix #2773 (send empty extension for image with no extension)
  src/ImageHelper.php
  tests/test-external-image.php
Labels: 2.x Future
